name: Safeliner Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      # Checks-out your repository
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ostrovskyde/fleet

      # Scan repo with Semgrep
      - name: scan
        run: |
          semgrep \
            --sarif --output report.sarif

      # Save report as pipeline artifact
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v4
        with:
          name: report.sarif
          path: report.sarif

  autofix:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ostrovskyde/safeliner-ci:0.0.1

    steps:
      # Checks-out your repository
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ostrovskyde/fleet

      # Get Sarif report from scanner job
      - name: Download report
        uses: actions/download-artifact@v4
        with: 
          name: report.sarif

      - name: Run Safeliner
        run: |
          echo $DFG_BUILDER_PATH